# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Create dist directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path ./dist
          
          # Copy only index.html to dist
          Copy-Item -Path index.html -Destination ./dist/
          
          # Verify the contents of dist
          Write-Output "Contents of dist directory:"
          Get-ChildItem -Path ./dist -Recurse | ForEach-Object { Write-Output $_.FullName }

      - name: Store dist contents
        run: |
          # Store the current directory
          $currentDir = Get-Location
          Write-Output "Current directory: $currentDir"
          
          # Create a temporary directory for dist contents
          $tempDir = Join-Path $env:RUNNER_TEMP "dist"
          New-Item -ItemType Directory -Force -Path $tempDir
          
          # Copy dist contents to temporary directory
          Copy-Item -Path "./dist/*" -Destination $tempDir -Recurse
          
          # Verify the contents
          Write-Output "Contents of temp directory:"
          Get-ChildItem -Path $tempDir -Recurse | ForEach-Object { Write-Output $_.FullName }

      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Switch to gh-pages branch
          git checkout gh-pages
          
          # Remove all files except .git
          Get-ChildItem -Path . -Exclude .git | Remove-Item -Recurse -Force
          
          # Copy from temporary directory
          $tempDir = Join-Path $env:RUNNER_TEMP "dist"
          Write-Output "Copying from temp directory: $tempDir"
          if (Test-Path $tempDir) {
              Copy-Item -Path "$tempDir\*" -Destination . -Recurse
          } else {
              Write-Error "Temp directory not found"
              exit 1
          }
          
          # Add all files
          git add .
          
          # Commit changes
          git commit -m "Deploy: ${{ github.sha }}"
          
          # Push changes
          git push origin gh-pages
