# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Create dist directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path ./dist
          
          # Copy only index.html to dist
          Copy-Item -Path index.html -Destination ./dist/
          
          # Verify the contents of dist
          Write-Output "Contents of dist directory:"
          Get-ChildItem -Path ./dist -Recurse | ForEach-Object { Write-Output $_.FullName }

      - name: Debug dist contents
        run: |
          Write-Output "Current directory:"
          Get-Location
          Write-Output "Contents of dist directory:"
          Get-ChildItem -Path ./dist -Recurse | ForEach-Object { Write-Output $_.FullName }
          Write-Output "File sizes:"
          Get-ChildItem -Path ./dist -Recurse | ForEach-Object { Write-Output "$($_.FullName): $($_.Length) bytes" }

      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Switch to gh-pages branch
          git checkout gh-pages
          
          # Remove all files except .git
          Get-ChildItem -Path . -Exclude .git | Remove-Item -Recurse -Force
          
          # Copy files from dist
          Copy-Item -Path ./dist/* -Destination . -Recurse
          
          # Add all files
          git add .
          
          # Commit changes
          git commit -m "Deploy: ${{ github.sha }}"
          
          # Push changes
          git push origin gh-pages
