name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check Runner
        run: |
          echo "Runner OS: $env:RUNNER_OS"
          echo "Runner Name: $env:RUNNER_NAME"
          echo "Runner Tool Cache: $env:RUNNER_TOOL_CACHE"
          Get-ComputerInfo | Select-Object OsName, OsVersion, OsArchitecture 